version: '2'
services:
  ciencia-postgresql:
    image: postgres:11.3
    # volumes:
    #     - ~/volumes/jhipster/ciencia/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=ciencia
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
